version: "3.4"
services:
  openethereum.dnp.dappnode.eth:
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: v3.1.0
    image: "openethereum.dnp.dappnode.eth:0.2.4"
    restart: always
    volumes:
      - "data:/root/.local/share/openethereum"
    environment:
      - EXTRA_OPTS=--warp-barrier 9850000
    ports:
      - "30303"
      - 30303/udp
      - 30304/udp
volumes:
  data: {}
